AWSTemplateFormatVersion: '2010-09-09'
Description: Parking Lot Management System - EC2 Deployment

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Deployment stage
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type
    AllowedValues: [t2.micro, t2.small, t2.medium]
  SSHLocation:
    Type: String
    Description: The IP address range that can be used to SSH to the EC2 instances (set to your IP for security)
  GitRepositoryUrl:
    Type: String
    Default: https://github.com/yourusername/parking-lot-system.git
    Description: URL of the Git repository containing the application code

Resources:
  ParkingTicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub parking-tickets
      AttributeDefinitions:
        - AttributeName: ticket_id
          AttributeType: S
        - AttributeName: license_plate
          AttributeType: S
      KeySchema:
        - AttributeName: ticket_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

      GlobalSecondaryIndexes:
        - IndexName: license_plate-index
          KeySchema:
            - AttributeName: license_plate
              KeyType: HASH
          Projection:
            ProjectionType: ALL
            
  ParkingLotSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0

  ParkingLotInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ParkingTableCrud
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:CreateTable
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:DescribeTable
                Resource:
                  - !GetAtt ParkingTicketsTable.Arn
                  - !Sub "${ParkingTicketsTable.Arn}/index/*"

  ParkingLotInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ParkingLotInstanceRole
          
  ParkingLotInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref ParkingLotSecurityGroup
      KeyName: !Ref KeyName
      ImageId: ami-06dd92ecc74fdfb36  # Amazon Linux 2023 in eu-central-1
      IamInstanceProfile: !Ref ParkingLotInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Log all output for debugging
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          
          # Set up environment variables
          echo "export DYNAMODB_TABLE=${ParkingTicketsTable}" > /etc/profile.d/parking-lot-env.sh
          echo "export AWS_REGION=${AWS::Region}" >> /etc/profile.d/parking-lot-env.sh
          
          GIT_REPO_URL="${GitRepositoryUrl}"
          git clone $GIT_REPO_URL /tmp/parking-lot-system
          echo "export GIT_REPO_PATH=/tmp/parking-lot-system" >> /etc/profile.d/parking-lot-env.sh

          # Set up the application
          echo "Setting up the application..."
          cd /tmp/parking-lot-system/deploy
          chmod +x ec2_setup.sh
          ./ec2_setup.sh
          
          echo "Setup complete! Check /var/log/user-data.log for details."
          
          # Create welcome message
          cat > /etc/motd << EOF
          =======================================================
          Welcome to Parking Lot Management System EC2 Instance!
          =======================================================
          
          Application Directory: /tmp/parking-lot-system
          Log files: /var/log/user-data.log, journalctl -u parking-lot
          
          =======================================================
          EOF
          
          # Display welcome message on login
          echo "cat /etc/motd" >> /home/ubuntu/.bashrc
            
Outputs:
  ParkingLotInstanceIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt ParkingLotInstance.PublicIp
  ParkingLotInstanceId:
    Description: Instance ID of the EC2 instance
    Value: !Ref ParkingLotInstance
  ParkingTicketsTable:
    Description: DynamoDB Table Name
    Value: !Ref ParkingTicketsTable
  WebsiteURL:
    Description: URL for the Parking Lot Management System
    Value: !Sub http://${ParkingLotInstance.PublicIp}:8000
